version: "1"
services:
  - type: web
    name: programacaoiii-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_PROFILE
        value: PROD
      - key: DATABASE_URL
        fromDatabase:
          name: programacaoiii-db
          property: connectionString
    healthCheckPath: /docs
databases:
  - name: programacaoiii-db
    databaseName: programacaoiii_db
    user: postgres